"""Build a self-contained HTML dashboard from a run output directory."""

from __future__ import annotations

import html
import json
from pathlib import Path

from tessera_app.markdown import render_markdown

_CSS = """
:root{--bg:#0f1115;--panel:#171a21;--ink:#e6e8eb;--muted:#9aa3af;--line:#262b35;--accent:#6ea8fe;--ok:#3fb950;--warn:#d29922;--err:#f85149}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
header{padding:28px 32px;border-bottom:1px solid var(--line)}
h1{margin:0;font-size:22px}h2{margin:28px 0 10px;font-size:18px}h3{margin:18px 0 8px;font-size:15px;color:var(--muted)}
.sub{color:var(--muted);margin-top:6px}
.wrap{display:flex;gap:0;min-height:calc(100vh - 86px)}
nav{width:200px;flex:none;border-right:1px solid var(--line);padding:18px 0}
nav a{display:block;padding:8px 24px;color:var(--ink);text-decoration:none;border-left:2px solid transparent}
nav a:hover{background:var(--panel);border-left-color:var(--accent)}
main{flex:1;padding:24px 32px;max-width:980px}
.cards{display:flex;flex-wrap:wrap;gap:12px;margin:12px 0 4px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:14px 16px;min-width:120px}
.card .k{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.04em}
.card .v{font-size:22px;font-weight:600;margin-top:4px}
.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:12px;font-weight:600}
.b-ok{background:rgba(63,185,80,.15);color:var(--ok)}.b-err{background:rgba(248,81,73,.15);color:var(--err)}
section.pack{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:8px 20px 18px;margin:18px 0}
table{border-collapse:collapse;width:100%;margin:8px 0;font-size:13px}
th,td{border:1px solid var(--line);padding:6px 10px;text-align:left}th{background:#1d2230;color:var(--muted)}
code{background:#1d2230;padding:1px 5px;border-radius:4px;font-size:13px}
pre.code{background:#0b0d11;border:1px solid var(--line);border-radius:8px;padding:12px;overflow:auto;font-size:12.5px}
ul{margin:6px 0 6px 18px}details{margin:8px 0}summary{cursor:pointer;color:var(--accent)}
.report{border-top:1px solid var(--line);margin-top:14px;padding-top:6px}
footer{color:var(--muted);padding:24px 32px;border-top:1px solid var(--line);font-size:13px}
"""

_REPORT_ORDER = [
    "index.md", "validation_report.md", "coverage_report.md",
    "data_quality_report.md", "dependencies_report.md",
    "execution_plans.md", "redactions_report.md", "retrieval_targets.md",
]


def build_dashboard(run_dir: Path, output_html: Path | None = None) -> Path:
    """Render run_dir into a single self-contained index.html. Returns its path."""
    run_dir = Path(run_dir)
    manifest_path = run_dir / "run_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {"project": str(run_dir), "packs": []}
    packs = manifest.get("packs", [])

    nav = "".join(f"<a href='#{p['pack']}'>{html.escape(p['pack'])}</a>" for p in packs)

    total_records = sum(p.get("record_count", 0) for p in packs)
    total_findings = sum(p.get("finding_count", 0) for p in packs)
    total_errors = sum(p.get("error_count", 0) for p in packs)

    cards = _cards({
        "Packs run": len([p for p in packs if p.get("ok")]),
        "Records": total_records,
        "Findings": total_findings,
        "Errors": total_errors,
    })

    sections = "".join(_pack_section(run_dir, p) for p in packs)
    if not packs:
        sections = "<p class='sub'>No packs were applicable to this project.</p>"

    doc = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Tessera Dashboard</title><style>{_CSS}</style></head>
<body>
<header><h1>Tessera Dashboard</h1>
<div class="sub">Project: <code>{html.escape(str(manifest.get('project','')))}</code></div>
{cards}</header>
<div class="wrap"><nav>{nav}</nav><main>{sections}</main></div>
<footer>Generated by tessera-app. Self-contained; no server required.</footer>
</body></html>"""

    out = output_html or (run_dir / "index.html")
    out.write_text(doc, encoding="utf-8")
    return out


def _cards(metrics: dict[str, int]) -> str:
    items = "".join(f"<div class='card'><div class='k'>{html.escape(k)}</div><div class='v'>{v}</div></div>"
                    for k, v in metrics.items())
    return f"<div class='cards'>{items}</div>"


def _pack_section(run_dir: Path, p: dict) -> str:
    name = p.get("pack", "")
    status = ("<span class='badge b-ok'>ok</span>" if p.get("ok")
              else f"<span class='badge b-err'>failed</span>")
    head = (f"<section class='pack' id='{html.escape(name)}'>"
            f"<h2>{html.escape(name)} {status}</h2>"
            f"<div class='sub'>{html.escape(p.get('reason',''))}</div>")

    if not p.get("ok"):
        return head + f"<p class='b-err'>{html.escape(p.get('error',''))}</p></section>"

    head += _cards({
        "Records": p.get("record_count", 0),
        "Findings": p.get("finding_count", 0),
        "Errors": p.get("error_count", 0),
    })

    pack_dir = Path(p.get("output_dir", "")) if p.get("output_dir") else run_dir / name
    reports = sorted(
        (a for a in p.get("artifacts", []) if a.endswith(".md")),
        key=lambda a: _REPORT_ORDER.index(a) if a in _REPORT_ORDER else 99,
    )
    body = ""
    for fname in reports:
        fpath = pack_dir / fname
        if not fpath.exists():
            continue
        rendered = render_markdown(fpath.read_text(encoding="utf-8"))
        open_attr = " open" if fname in ("index.md", "validation_report.md") else ""
        body += (f"<details{open_attr}><summary>{html.escape(fname)}</summary>"
                 f"<div class='report'>{rendered}</div></details>")

    return head + body + "</section>"
