name: PR Build
on:
  pull_request_target:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout PR code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: true
      - name: Build
        run: ./build.sh
